# Generated by Django 3.1.5 on 2021-02-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_studentlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='slug',
            field=models.SlugField(default='discipline', unique=True),
        ),
    ]
