# Generated by Django 3.1.5 on 2021-02-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_discipline_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='slug',
            field=models.SlugField(default=None, unique=True),
        ),
    ]
